"""
Файл с настройками проекта
"""

from os.path import abspath, dirname


BASE_DIR = dirname(dirname(abspath(__file__)))
SOURCE_DIR = BASE_DIR + '\\Исходники\\'
RESULT_DIR = BASE_DIR + '\\Результаты\\'
REPORTS = '\\Отчёты\\'
REPORTS_FINAL = '\\Отчёты финальные\\'
REPORT_DIR = RESULT_DIR + REPORTS
REPORT_DIR_FINAL = RESULT_DIR + REPORTS_FINAL
ARCHIVE_DIR = BASE_DIR + '\\Архив\\'

NUM_MONTHS = 3
TARGET_STOCK = 1

EAN = 'EAN штуки'
PRODUCT = 'Наименование товара'
SU = 'SU штуки'
MSU = 'MSU штуки'
LEVEL_0 = '0-й уровень'
LEVEL_1 = '1-й уровень'
LEVEL_2 = '2-й уровень'
LEVEL_3 = '3-й уровень'
HOLDING = 'Код основного холдинга'
NAME_HOLDING = 'Наименование основного холдинга'
CODES = 'Код Точки доставки / Плательщика / Холдинга / Основного холдинга'
BASE_PRICE = 'Базовая цена без НДС, шт'
ELB_PRICE = 'Цена NIV Эльбрус с НДС, шт'
WHS = 'Склад'
LINK = 'Сцепка Склад-ШК'
LINK_HOLDING = 'Сцепка Склад-Наименование холдинга-ШК'
FULL_REST = 'Общий остаток, шт'
AVAILABLE_REST = 'Доступный остаток, шт'
QUOTA = 'Квота, шт'
FREE_REST = 'Свободный остаток, шт'
SOFT_RSV = 'Мягкий резерв, шт'
HARD_RSV = 'Жесткий резерв, шт'
SOFT_HARD_RSV = 'Мягкие + жёсткие резервы, шт'
QUOTA_BY_AVAILABLE = 'Резерв квота с учётом доступного стока'
TOTAL_RSV = 'В резерве всего'
DATE_RSV = 'Максимальная дата резерва'
CUTS = 'Урезания '
SALES = 'Продажи '
CUTS_SALES = 'Урезания + продажи '
AVARAGE = 'Средние '
OVERSTOCK = f'Сток свыше {TARGET_STOCK} месяца (-ев) продаж, шт'
FULL_REST_MSU = FULL_REST.replace('шт', 'msu')
OVERSTOCK_MSU = OVERSTOCK.replace('шт', 'msu')
MATRIX = 'Матрица Эльбрус'
MATRIX_LY = 'Матрица Эльбрус (Лоджистик-Юг)'
FACTOR = 'Фактор'
FACTOR_NUM = 'Номер фактора'
REF_FACTOR = 'Ссылка на фактор'
FACTOR_STATUS = 'Статус'
DATE_CREATION = 'Дата создания фактора'
DATE_START = 'Дата начала действия фактора'
DATE_EXPIRATION = 'Дата окончания действия фактора'
ADJUSTMENT_PBI = 'Корректировка плана PBI, шт'
FACTOR_PERIOD = 'Период фактора'
DESCRIPTION = 'Комментарий фактора'
PLAN_NFE = 'План NFE, шт'
FACT_NFE = 'Факт NFE, шт'
USER = 'Ответственный пользователь'
SALES_PBI = 'Продажи PBI, шт'
CUTS_PBI = 'Урезания PBI, шт'
RESERVES_PBI = 'Резервы PBI, шт'
PURPOSE_PROMO = 'Цель фактора (для акций)'
ALL_CLIENTS = '<ВСЕ КЛИЕНТЫ>'
NAME_TRAD = '<ТРАДИЦИЯ>'
SALES_FACTOR_PERIOD = 'Продажи клиента(-ов) по периоду фактора'
RSV_FACTOR_PERIOD = 'Резервы клиента(-ов)'
RSV_FACTOR_PERIOD_CURRENT = 'Резервы клиента(-ов) текущего месяца'
RSV_FACTOR_PERIOD_TOTAL = 'Резервы клиента(-ов) с квотой'
AVG_FACTOR_PERIOD = 'Средние продажи + урезания за 3 месяца по клиенту(-ам)'
AVG_FACTOR_PERIOD_WHS = 'Средние продажи + урезания за 3 месяца по складу'
PAST = 'Прошедший'
CURRENT = 'Текущий'
FUTURE = 'Будущий'
TRANZIT_CURRENT = 'Транзит текущего месяца, шт'
TRANZIT_NEXT = 'Транзит следующего месяца, шт'
TRANZIT = 'Транзит всего, шт'
INACTIVE_PURPOSE = 'Минимизация потерь'
DATE_REGISTRY = 'Дата регистрации объёма'
QUANT_REGISTRY = 'Зарегистрированное количество на дату, шт'
SOFT_HARD_RSV_CURRENT = 'Мягкие + жёсткие резервы текущего периода, шт'
SOFT_HARD_RSV_FUTURE = 'Мягкие + жёсткие резервы будущего периода, шт'
LINES = 'Линейки'
RSV_FACTOR_PERIOD_FUTURE = 'Резервы клиента(-ов) будущего месяца'
CANCEL_STATUS = 'Отменен(а)'
SALES_CURRENT_FOR_PAST = 'Продажи текущего месяца для прошедших факторов, шт'
SALES_BY_DATE = 'Продажи, шт'
CUTS_BY_DATE = 'Урезания, шт'
DATE_SALES = 'Дата продажи или урезания'
EXCLUDE_STRING = 'Строка исключена'
EX_LINK_DATE = 'Исключение по Сцепке Дата-Склад-Клиент-Штрихкод'
EX_NAME_HOLDING = 'Исключение Клиента'
EX_LINK = 'Исключение по Сцепке Склад-EAN'
EX_EAN = 'Исключение по EAN'
EX_RSV = ('Исключение Мягких резервов или квот по Сцепке'
          ' Дата-Склад-Клиент-Штрихкод')
PIC_IN_BOX = 'Количество штук в коробке'
PIC_IN_LAYER = 'Количество штук в слое'
PIC_IN_PALLET = 'Количество штук в паллете'
MIN_ORDER = 'Минимальная единица заказа'
CRITICAL_EAN = 'Штриккод в критикал листе'
QUOTA_WITH_REST = 'Квота обеспеченная товаром, шт'
QUOTA_WITHOUT_REST = 'Квота НЕ обеспеченная товаром, шт'
EXPECTED_DATE = 'Дата резерва (ожидаемой доставки)'
PG_PROGRAMM = 'PG программа клиента'
WORD_YES = 'ДА'

TABLE_ASSORTMENT = 'Ассортимент.xlsx'
TABLE_DIRECTORY = 'Справочник_ШК.xlsx'
TABLE_HOLDINGS = 'Холдинги.xlsx'
TABLE_PRICE = 'Прайс.xlsx'
TABLE_PURCHASES = 'Закупки.xlsx'
TABLE_REMAINS = 'Остатки.xlsx'
TABLE_SALES_HOLDINGS = 'Продажи по клиентам и складам.xlsx'
TABLE_SALES = 'Продажи по складам.xlsx'
TABLE_RESERVE = 'Резервы.xlsx'
TABLE_FACTORS = 'Факторы.xlsx'
TABLE_REGISTRY_FACTORS = 'Реестр по факторам.xlsx'


ACCESSORY_DIR = '\\Вспомогательные данные\\'
TABLE_RESERVE_CURRENT = ACCESSORY_DIR + 'Резервы текущего месяца.xlsx'
TABLE_RESERVE_FUTURE = ACCESSORY_DIR + 'Резервы следующего месяца.xlsx'
TABLE_LINES = ACCESSORY_DIR + 'Линейки.xlsx'
TABLE_EXCLUDE = ACCESSORY_DIR + 'Исключения проверки.xlsx'
TABLE_FULL_SALES_CLIENTS = ACCESSORY_DIR + 'Полные продажи по клиентам.xlsx'
TABLE_FULL_SALES = ACCESSORY_DIR + 'Полные продажи по складам.xlsx'
TABLE_MHL = ACCESSORY_DIR + 'MHL_ListA.xlsx'

ORDER_FORM = '\\Бланк заказа\\'
ORDER_FORM_DIR = REPORTS + ORDER_FORM
TABLE_SALES_BY_DATE = ORDER_FORM_DIR + 'Продажи по датам.xlsx'
TABLE_EXCEPTIONS = ORDER_FORM_DIR + 'Исключения.xlsx'
REPORT_ORDER_FORM = ORDER_FORM + 'Бланк заказа.xlsx'
TABLE_RSV_BY_DATE = ORDER_FORM_DIR + 'Резервы по датам.xlsx'
TABLE_ORDER_FACTORS = ORDER_FORM + 'Прогноз по факторам.xlsx'

PS_DIR = '\\Потенциальные продажи\\'
PS_DIR_FUTURE = '\\Будущие потенциальные продажи\\'
REPORT_POTENTIAL_SALES = PS_DIR + 'Потенциальные продажи.xlsx'
REPORT_ELBRUS_FACTORS = PS_DIR + 'Факторы Эльбрус.xlsx'
REPORT_BASE_FACTORS = PS_DIR + 'Факторы База.xlsx'
FUTURE_REPORT_PS = PS_DIR_FUTURE + 'Потенциальные продажи.xlsx'
FUTURE_ELB_PS = PS_DIR_FUTURE + 'Факторы Эльбрус.xlsx'
FUTURE_BASE_PS = PS_DIR_FUTURE + 'Факторы База.xlsx'
REPORT_CHECK_FACTORS = 'Проверка факторов.xlsx'
REPORT_NOT_SOLD_PAST = 'Не продано с прошлого месяца.xlsx'
REPORT_NOT_SOLD_CURRENT = 'Не продано с текущего месяца.xlsx'
REPORT_TRACKING_NOT_SOLD = 'Трекинг продаж по факторам.xlsx'

DATE_COL = [
    DATE_RSV, DATE_CREATION, DATE_START, DATE_EXPIRATION, DATE_REGISTRY,
    DATE_SALES, EXPECTED_DATE
]

ACTIVE_STATUS = [
    'Полностью согласован(а)',
    'Завершен(а)'
]
